### ISSUE TITLE
Retrieve `git config user.*` for commits

### ISSUE THREAD

**Issue by EstebanBorai** [whizzes/cargo-tag#49]
When building instances of the Git Client it would be great to reuse
existing `git` `user` details.

https://github.com/whizzes/cargo-tag/blob/main/src/git.rs#L31-L41

**Comment by oylenshpeegul** [comment]
So would you want to get rid of the environment variables or have them override? Maybe something like this

```rust
    let email = if let Ok(email) = std::env::var("CARGO_TAG_EMAIL") {
        email
    } else {
        cfg.get_entry("user.email")?
            .value()
            .ok_or("user.email not utf8")?
            .to_string()
    };
```

**Comment by EstebanBorai** [comment]
Hi @oylenshpeegul!

Having them overriden would be ideal.

Do you want to work on this? I can assign you if thats the case!

**Comment by oylenshpeegul** [comment]
Sure, I'll give it a go!

**Comment by EstebanBorai** [comment]
Currently we have `from_env` associated function.

I think having a `from_git_config` associated function would be ideal.

By having different functions, each with its own behavior we would have predictable behavior and supress any side-effects.

**Comment by oylenshpeegul** [comment]
Oh, I was thinking the other way...just have `open` do the `if-then-else` above and ditching `from_env`
